united-build: 
language: generic
sudo: required
services:
- docker
before_install:
- wget -c -P /tmp/ https://github.com/UnitedRPMs/unibuild/releases/download/auth/auth.enc && pushd /tmp/ && openssl aes-256-cbc -d -in auth.enc -pass pass:$who_are_you -out auth
- docker pull davidva/unibuild-26
script:
- docker run -v /tmp:/tmp --cap-add=SYS_ADMIN davidva/unibuild-26 /bin/sh -c "mv -f /tmp/auth /root/.megarc && rm -f urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/mock-unitedrpms -s mock-unitedrpms.spec -r true -d 'dist .fc26' -c true"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8bbc656ea277114ba4fd
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

