name: build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          docker run -v $(pwd):/root/enjoy --cap-add=SYS_ADMIN davidva/unibuild-35 /bin/sh -c "rm -f urpms && wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x urpms && /urpms -g UnitedRPMs/kodi-pvr-addons -s kodi-pvr-addons.spec -r true -d 'dist .fc35' -c true -u true -w true"
